export enum ErrorCodes {
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',

  FILE_WRITE_FAILED = 'FILE_WRITE_FAILED',

  REQUEST_FAILED = 'REQUEST_FAILED',
  UNEXPECTED_ERROR = 'UNEXPECTED_ERROR',

  VALIDATION_ERROR = 'VALIDATION_ERROR',
  EMPTY_RESPONSE = 'EMPTY_RESPONSE',
}
